### ISSUE TITLE
IE9 false positive on weird UA

### ISSUE THREAD

**Issue by dsingleton** [slightlyoff/suchi.js#14]
We (@alphagov) had a bug report from a user of IE10 being detected as IE9 and getting prompted to upgrade. This is the UA automatically captured as part of the report:

```
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/6.0; EIE10;ENUSWOL) 
```

It clearly matches the IE9 regex, but `Trident/6.0` + `EIE10` corroborates IE10. It makes me wonder if matching on Trident versions here might help?

I know Suchi isn't trying to be [exhaustive](https://github.com/slightlyoff/suchi.js#wont-some-users-fall-through-the-cracks), which is sensible for false negatives, but false positives are going to impact/annoy a user. 

(This is half question, half bug report, thoughts?)

**Comment by slightlyoff** [comment]
yeah, false-positives are fatal. Thanks for filing this.

**Comment by slightlyoff** [comment]
So it looks like this is the result of IE (many) Compatibility Mode triggers. I'm adding tests and fixing the regexes, meanwhile I've verified that gov.uk isn't (generally) getting demoted by IE via https://iecvlist.microsoft.com/IE11/1375395130872/iecompatviewlist.xml. The only gov.uk entries are:

``` xml
    <domain uaString="Firefox Token">scotcourts.gov.uk</domain>
    <domain uaString="Firefox Token">dudley.gov.uk</domain>
```

**Comment by dsingleton** [comment]
Thanks for the thorough investigation and fix. I owe you a :beer:

**Comment by slightlyoff** [comment]
Just FYI, the update is pretty aggressive about opting browsers into "old" bucket. It's now including old Safari, old Android Browser, as well as IE9. Let me know if you'd like it dialed back.

**Comment by bradwright** [comment]
@slightlyoff it appears to be lumping Chrome 33 (latest at time of writing is 35) into the old bucket too. I wonder if some kind of offset per browser is sensible (given Chrome will be pretty secure/functional a few versions back).

**Comment by bradwright** [comment]
Sorry, I'll file a separate bug about that.
