### ISSUE TITLE
Need API Clarity

### ISSUE THREAD

**Issue by bkardell** [slightlyoff/suchi.js#9]
Currently config itself is an array, and we build a single unified "config" view out of them... Part of this is incomplete because the examples show onlagging but since the value type is function, nothing is dealing with this.  Nothing currently explains how this works, so I am confused as to where to go with it...

What happens if I do something like:

```
suchiConfig.push({
    treatGCFAsLagging: true, 
    onlagging: function() {
      // Callback that's fired when Suchi detects as
      alert('I think your browser sucks - even with GCF');
    }
});

suchiConfig.push({
    treatGCFAsLagging: false, 
    onlagging: function() {
      // Callback that's fired when Suchi detects as
      alert('I think your browser sucks - not considering GCF');
    }
});
```

As a dev, I would kind of expect those callbacks to happen only in the event that the config object that they belong to says it should - not if any of them pass, all of them execute... If we can explain it nicely, ok, but it feels a little unintuitive to have multiple configs like that... As it is, I am a little unsure which thing to implement and contribute or even open an issue for.  

Could we just simplify it to something like...

``` html
<div id="promptId"></div>
<script src="src/suchi.min.js"></script>
<script>
  suchi.check({
    onlagging: function() {
      // Callback that's fired when Suchi detects as
      alert('your browser sucks');
    }
  });
</script>

```

Or even just keep the idea of multiple "checks" (original 'When I would expect..' above) as opposed to "configs" and keep it possible to async load.

**Comment by slightlyoff** [comment]
The current logic is badly broken...which is what I get for not having tests about the array-of-functions design yet.

The design ideas still seem right, though. In general, we should _never_ introduce any `<script>` elements into the page that will block layout for any meaningful period of time. To get there, the config object gets populated before it's parsed and the loading for `suchi.min.js` is async. Once it loads, it unwinds whatever options were set. The design right now is "last configurer wins", except for arrays, where it tries to merge them.

I honestly don't know if this is sane or not. Either way, the current logic is busted. Let me check in a fix for the option parsing logic and we can discuss wether or not last-configurer-wins should always be the case (in which case, perhaps we should just have folks stomp on `suchiConfig` to accomplish this, avoiding all merging).

**Comment by bkardell** [comment]
On Thu, Feb 21, 2013 at 11:05 AM, Alex Russell notifications@github.comwrote:

> The current logic is badly broken...which is what I get for not having
> tests about the array-of-functions design yet.
> 
> The design ideas still seem right, though. In general, we should _never_introduce any
> <script> elements into the page that will block layout for any meaningful
> period of time. To get there, the config object gets populated before it's
> parsed and the loading for suchi.min.js is async. Once it loads, it
> unwinds whatever options were set. The design right now is "last configurer
> wins", except for arrays, where it tries to merge them.
> 
> I honestly don't know if this is sane or not. Either way, the current
> logic is busted. Let me check in a fix for the option parsing logic and we
> can discuss wether or not last-configurer-wins should always be the case
> (in which case, perhaps we should just have folks stomp on suchiConfig to
> accomplish this, avoiding all merging).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/slightlyoff/suchi.js/issues/9#issuecomment-13896605.

I kinda like the idea of an array of configs that can respond independently
- interesting possibilities there... you can always choose to add or stomp
  suchiConfig[0] so that could be the best of both worlds.  Might consider
  pluralizing suchiConfigs if that is the chosen route though.

## 

Brian Kardell :: @briankardell :: hitchjs.com

**Comment by slightlyoff** [comment]
Oh, interesting...pluralizing `suchiConfig` does seem like a sane way out...although...does that mean we just have multiple prompts potentially? I guess that's not the worst thing ever, but it sure might be confusing.

Another option is to just not bother with merging. The current behavior is friendly to scripts that just want to run an `isOld()` call (via an `islagging` handler) and don't want to coordinate, but pretty grotty for all other sorts of configuration collaboration. Would save a tiny bit of code weight.

**Comment by bkardell** [comment]
On Thu, Feb 21, 2013 at 11:13 AM, Alex Russell notifications@github.comwrote:

> Oh, interesting...pluralizing suchiConfig does seem like a sane way
> out...although...does that mean we just have multiple prompts potentially?
> I guess that's not the worst thing ever, but it sure might be confusing.
> 
> It does - but I think that is easy to doc, and actually potentially
> useful... For example, if you had just one part of your page that was using
> something cutting edge, you might choose to say "hey - you're missing this
> awesome feature _right here_ because we just can't possibly fill it..." I
> think that would make it flexible/powerful enough that you would see some
> experimentation and interesting patterns.  Worthwhile? In the right spirit
> - dunno.
> 
> Another option is to just not bother with merging. The current behavior is
> friendly to scripts that just want to run an isOld() call (via an
> islagging handler) and don't want to coordinate, but pretty grotty for
> all sorts of configuration collaboration. Would save a tiny bit of code
> weight.

Easy enough to manually default missing values too instead of a universal
pattern, but sure.

>  —
> Reply to this email directly or view it on GitHubhttps://github.com/slightlyoff/suchi.js/issues/9#issuecomment-13897057.

## 

Brian Kardell :: @briankardell :: hitchjs.com

**Comment by slightlyoff** [comment]
Interesting. Pluralizing `suchiConfig` sounds like it's the right way to go....so, we avoid flattening, and instead each process each config object independently. I can think of risks around `allowCookies`, but they're not anything we aren't already exposed to in the current thinking. I like this. Will remove flattening to a single config, but keep defaults merging on a per-config object basis.

Other thoughts? @phae?

**Comment by phae** [comment]
I like the feature specific example above. It's a usage we suggested in our earlier conversations, so if this makes it easier to do that then +1
